version: '3.8'

services:
  traefik:
    image: traefik:v3.6.13
    command:
      # Enable Docker Swarm mode
      - "--log.level=DEBUG"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy-private"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.file.directory=/etc/traefik/dynamic" # Point to the file
      - "--providers.file.watch=true"
      - "--serverstransport.insecureskipverify=true"
      # Enable the File Provider
      #      - "--providers.file.directory=/etc/traefik/dynamic"
      #      - "--providers.file.watch=true"
      # Entrypoints for HTTP and HTTPS
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # (Optional) Automatic SSL via Let's Encrypt
      - "--certificatesresolvers.mydnschallenge.acme.dnschallenge=true"
      - "--certificatesresolvers.mydnschallenge.acme.dnschallenge.provider=route53"
      #      - "--certificatesresolvers.mydnschallenge.acme.email="
      - "--certificatesresolvers.mydnschallenge.acme.storage=/letsencrypt/acme.json"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION} # Or your specific region
      - AWS_HOSTED_ZONE_ID=${HOSTED_ZONE_ID}
      - TRAEFIK_CERTIFICATESRESOLVERS_MYDNSCHALLENGE_ACME_EMAIL=${ACME_EMAIL}
      # This line is key: it tells Traefik to look for the cert containing these domains
      - "TRAEFIK_CERTIFICATESRESOLVERS_MYDNSCHALLENGE_ACME_DOMAINS_0_MAIN=${DOMAIN_NAME}"
      - "TRAEFIK_CERTIFICATESRESOLVERS_MYDNSCHALLENGE_ACME_DOMAINS_0_SANS=*.${DOMAIN_NAME}"
    ports:
      #      - "9888:80"
      #      - "443:443"
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: udp
        mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/docker/traefik/dynamic:/etc/traefik/dynamic:ro
      - /mnt/docker/traefik/lets-encrypt:/letsencrypt
    #      - lets-encrypt-data:/letsencrypt
    networks:
      - proxy_private
      - proxy_public
    #      - internal-only-torrent-network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik-dashboard.rule=Host(`${TRAEFIK_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
        - "traefik.http.routers.traefik-dashboard.tls=true"
        # This is the "magic" service name Traefik uses for itself
        - "traefik.http.routers.traefik-dashboard.service=api@internal"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      placement:
        constraints:
          - node.labels.docker_mount == true
          - node.role == manager
          - node.labels.type != restricted

  traefik-manager:
    image: ghcr.io/chr0nzz/traefik-manager:latest
    restart: unless-stopped
    #    ports:
    #      - "5000:5000"
    environment:
      - COOKIE_SECURE=false
    volumes:
      - /mnt/docker/traefik/dynamic/dynamic.yml:/app/config/dynamic.yml
      - /mnt/docker/traefik/manager:/app/config
    #      - /path/to/traefik-manager/backups:/app/backups
    networks:
      - proxy_private
    #      - proxy_public
    #      - internal-only-torrent-network
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.traefik-manager.rule=Host(`${MANAGER_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.traefik-manager.entrypoints=websecure"
        - "traefik.http.routers.traefik-manager.tls=true"
        - "traefik.http.routers.traefik-manager.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.traefik-manager.loadbalancer.server.port=5000"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.traefik-manager.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.traefik-manager.tls.domains[0].sans=*.${BASE_DOMAIN}"
      replicas: 1
      placement:
        constraints:
          - node.labels.docker_mount == true
          - node.role == manager
          - node.labels.type != restricted

networks:
  proxy_public:
    driver: overlay
    attachable: true
    name: proxy_public
  proxy_private:
    driver: overlay
    attachable: true
    name: proxy_private