version: '3.8'

services:
  nginx_proxy_manager:
    image: 'jc21/nginx-proxy-manager:2.14.0'
    networks:
      - proxy_public
      - proxy_private
      - maria_db_net
      - dns_network
    ports:
#      - target: 80
#        published: 80
#        protocol: tcp
#        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
      - target: 81
        published: 81
        protocol: tcp
        mode: ingress
      - target: 1883
        published: 1883
        protocol: tcp
        mode: ingress
      - target: 5683
        published: 5683
        protocol: udp
        mode: ingress
    volumes:
      - nginx_nfs:/data:subpath=data
      - nginx_nfs:/etc/letsencrypt:subpath=letsencrypt
    environment:
      DB_MYSQL_HOST: "maria-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "node_proxy_manager"
      DB_MYSQL_PASSWORD: /run/secrets/maria_db_user_node_proxy_manager_password
      DB_MYSQL_NAME: "node_proxy_manager"
      PUID: 1000
      PGID: 1000
      TZ: America/Denver
    deploy:
      placement:
        constraints: [node.role == manager]

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    ports:
#      - "51820:51820/udp"
      - "51821:51821/tcp" # Web UI
    networks:
      - vpn_network
      - proxy_private
    environment:
      - WG_HOST=vpn.derek-crew.com
#      - PASSWORD_HASH=$$2y$$10$$... # Use a hash for security
      - PORT=51821
      - INSECURE=true
#    volumes:
#      - wg-data:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  proxy_public:
    driver: overlay
    attachable: true
    name: proxy_public
  proxy_private:
    driver: overlay
    attachable: true
    name: proxy_private
  maria_db_net:
    external: true
    name: database_maria_db_net
  dns_network:
    external: true
    name: dns_dns_net
  vpn_network:
    driver: overlay
    attachable: true
    name: vpn_network

volumes:
  nginx_nfs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_ADDRESS},nfsvers=3,nolock,soft,rw"
      device: ":${PROXY_DATA_NFS_DIRECTORY}"