version: '3.8'

services:
  nextcloud:
    image: nextcloud
#    container_name: nextcloud
    restart: unless-stopped
    networks:
      - next-cloud-network
      - proxy-private
    depends_on:
      - nextclouddb
      - redis
    ports:
      - 8081:80
    # volumes:
      # - ./html:/var/www/html
      # - ./custom_apps:/var/www/html/custom_apps
      # - ./config:/var/www/html/config
      # - ./data:/var/www/html/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_HOST=nextclouddb
      - REDIS_HOST=redis
    deploy:
      placement:
        constraints:
          - node.labels.docker_mount == true
          - node.labels.type != restricted
      replicas: 1
      restart_policy:
        condition: on-failure

  nextclouddb:
    image: mariadb
#    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - next-cloud-network
    volumes:
      - /opt/mysql/next-cloud:/var/lib/mysql
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    deploy:
      placement:
        constraints:
          - node.labels.database_node == true
      replicas: 1
      restart_policy:
        condition: on-failure

  collabora:
    image: collabora/code
#    container_name: collabora
    restart: unless-stopped
    networks:
      - next-cloud-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - password=password
      - username=nextcloud
      - domain=${DOMAIN}
      - extra_params=--o:ssl.enable=true
#    ports:
#      - 9980:9980
    deploy:
      placement:
        constraints:
          - node.labels.docker_mount == true
          - node.labels.type != restricted
      replicas: 1
      restart_policy:
        condition: on-failure

  redis:
    image: redis:alpine
#    container_name: redis
    # volumes:
    #   - ./redis:/data
    networks:
      - next-cloud-network
    deploy:
      placement:
        constraints:
          - node.labels.type != restricted
      replicas: 1
      restart_policy:
        condition: on-failure

  # nginx-proxy:
  #   image: 'jc21/nginx-proxy-manager:latest'
  #   container_name: nginx-proxy
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Los_Angeles
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'
  #     - '81:81'
  #     - '443:443'
  #   volumes:
  #     - ./data:/data
  #     - ./letsencrypt:/etc/letsencrypt

networks:
  next-cloud-network:
    driver: overlay
    name: next-cloud-network
  proxy-private:
    external: true
    name: proxy_private