version: '3.8'

services:
  nextcloud:
    image: nextcloud
#    container_name: nextcloud
    restart: unless-stopped
    networks:
      - next-cloud-network
      - proxy-private
    depends_on:
      - nextclouddb
      - redis
    ports:
      - 8081:80
    volumes:
#      - /mnt/docker/next-cloud/core:/var/www/html
#      - /mnt/docker/next-cloud/custom_apps:/var/www/html/custom_apps
#      - /mnt/docker/next-cloud/config:/var/www/html/config
#      - /mnt/docker/next-cloud/data:/var/www/html/data
      - next-cloud-data:/var/www/html
#      - next-cloud-data:/var/www/html/custom_apps:subpath=custom_apps
#      - next-cloud-data:/var/www/html/config:subpath=config
#      - next-cloud-data:/var/www/html/data:subpath=data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_HOST=nextclouddb
      - REDIS_HOST=redis
      - NEXTCLOUD_TRUSTED_DOMAINS=${TRUSTED_DOMAINS}
    deploy:
      labels:
        - "traefik.enable=true"
#        # The URL you will use to access Nextcloud
        - "traefik.http.routers.nextcloud.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.nextcloud.entrypoints=websecure"
        - "traefik.http.routers.nextcloud.tls=true"
#        - "traefik.http.routers.nextcloud.tls.certresolver=nextcloud"
#        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
#        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
      placement:
        constraints:
          - node.labels.docker_mount == true
          - node.labels.type != restricted
      replicas: 1
      restart_policy:
        condition: on-failure

  nextclouddb:
    image: mariadb
#    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - next-cloud-network
    volumes:
      - /opt/mysql/next-cloud:/var/lib/mysql
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    deploy:
      placement:
        constraints:
          - node.labels.database_node == true
      replicas: 1
      restart_policy:
        condition: on-failure

  collabora:
    image: collabora/code
#    container_name: collabora
    restart: unless-stopped
    networks:
      - next-cloud-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - password=password
      - username=nextcloud
      - domain=${DOMAIN}
      - extra_params=--o:ssl.enable=true
#    ports:
#      - 9980:9980
    deploy:
      placement:
        constraints:
          - node.labels.docker_mount == true
          - node.labels.type != restricted
      replicas: 1
      restart_policy:
        condition: on-failure

  redis:
    image: redis:alpine
#    container_name: redis
    # volumes:
    #   - ./redis:/data
    networks:
      - next-cloud-network
    deploy:
      placement:
        constraints:
          - node.labels.type != restricted
      replicas: 1
      restart_policy:
        condition: on-failure

  # nginx-proxy:
  #   image: 'jc21/nginx-proxy-manager:latest'
  #   container_name: nginx-proxy
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Los_Angeles
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'
  #     - '81:81'
  #     - '443:443'
  #   volumes:
  #     - ./data:/data
  #     - ./letsencrypt:/etc/letsencrypt

networks:
  next-cloud-network:
    driver: overlay
    name: next-cloud-network
  proxy-private:
    external: true
    name: proxy_private

volumes:
  next-cloud-data:
    driver: local
    name: next_cloud_nfs_data
    driver_opts:
      type: nfs
      o: "addr=${NFS_ADDRESS},nfsvers=3,nolock,soft,rw" # Replace with your NFS Server IP
      device: ":${NEXT_CLOUD_NFS_DIRECTORY}"