version: '3.8'

services:
  agent:
    image: portainer/agent:2.39.0-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.39.0-alpine
    command: -H tcp://tasks.agent:9001 --tlsskipverify
#    ports:
#      - "9443:9443"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      - dns_network
      - proxy_private
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.tls=true"
        - "traefik.http.routers.portainer.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.portainer.loadbalancer.server.port=80"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.portainer.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.portainer.tls.domains[0].sans=*.${BASE_DOMAIN}"
      mode: replicated
      replicas: 1
      placement:
        constraints:
          # This ensures the UI only runs on a node with the Manager role
          - node.role == manager

networks:
  agent_network:
    driver: overlay
    attachable: true
  dns_network:
    external: true
    name: dns_dns_net
  proxy_private:
    external: true
    name: proxy_private

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_ADDRESS},nfsvers=4,nolock,soft,rw" # Replace with your NFS Server IP
      device: ":${PORTAINER_NFS_DIRECTORY}"