version: '3.8'

services:
  actual_server:
    image: actualbudget/actual-server:latest
#    ports:
#      - "5006:5006"
    volumes:
      - /mnt/docker/actual-budget/data:/data
    networks:
      - business_network
      - proxy_private
      - kuma_network
    environment:
      # Set this to true if you are running behind a reverse proxy (recommended)
#      - ACTUAL_HTTPS_KEY=/data/selfhost.key
#      - ACTUAL_HTTPS_CERT=/data/selfhost.crt
      - ACTUAL_PORT=5006
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.actual_server.rule=Host(`${ACTUAL_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.actual_server.entrypoints=websecure"
        - "traefik.http.routers.actual_server.tls=true"
        - "traefik.http.routers.actual_server.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.actual_server.loadbalancer.server.port=5006"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.actual_server.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.actual_server.tls.domains[0].sans=*.${BASE_DOMAIN}"
        - "kuma.business.group.name=Business"
        - "kuma.actual_budget.http.name=Actual Budget"
        - "kuma.actual_budget.http.url=http://actual_server:5006"
        - "kuma.actual_budget.http.interval=300"
        - "kuma.actual_budget.http.parent_name=business"
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      placement:
        constraints:
          - node.labels.docker_mount == true
          - node.labels.type != restricted
#volumes:
#  n8n_data:
#    driver: local

networks:
  business_network:
    driver: overlay
    name: business-network
  proxy_private:
    external: true
  kuma_network:
    external: true
    name: kuma_network