version: '3.8'

services:
  actual_server:
    image: actualbudget/actual-server:latest
#    ports:
#      - "5006:5006"
    volumes:
      - /mnt/docker/actual-budget/data:/data
    networks:
      - business_network
    environment:
      # Set this to true if you are running behind a reverse proxy (recommended)
#      - ACTUAL_HTTPS_KEY=/data/selfhost.key
#      - ACTUAL_HTTPS_CERT=/data/selfhost.crt
      - ACTUAL_PORT=5006
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
#volumes:
#  n8n_data:
#    driver: local

networks:
  business_network:
    driver: overlay
    name: business-network