version: '3.8'

services:
  it-tools:
    image: corentinth/it-tools:2024.10.22-7ca5933
    networks:
      - proxy_private
      - tools
#    ports:
#      - target: 80
#        published: 8080
#        protocol: tcp
#        mode: host
    deploy:
      mode: replicated
      replicas: 1
#      placement:
#        constraints:
#          - node.role == worker
      restart_policy:
        condition: on-failure

  heimdall:
    image: lscr.io/linuxserver/heimdall:2.7.6
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - heimdall_nfs:/config:subpath=config
    networks:
      - proxy_private
#    ports:
#      - "8080:80"
#      - "8443:443"
    deploy:
      mode: replicated
      replicas: 1
#      placement:
#        constraints:
#          - node.role == manager # Often best to keep dashboards on managers
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

networks:
    proxy_private:
      external: true
      name: proxy_private
    tools:
      name: tools-network
      driver: overlay
      attachable: true

volumes:
  heimdall_nfs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_ADDRESS},nfsvers=3,nolock,soft,rw"
      device: ":${HEIMDALL_CONFIG_NFS_DIRECTORY}"