version: '3.8'

services:
  it-tools:
    image: corentinth/it-tools:2024.10.22-7ca5933
    networks:
      - proxy_private
      - tools
#    ports:
#      - target: 80
#        published: 8080
#        protocol: tcp
#        mode: host
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.it-tools.rule=Host(`${IT-TOOLS_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.it-tools.entrypoints=websecure"
        - "traefik.http.routers.it-tools.tls=true"
        - "traefik.http.routers.it-tools.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.it-tools.loadbalancer.server.port=80"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.it-tools.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.it-tools.tls.domains[0].sans=*.${BASE_DOMAIN}"
      placement:
        constraints:
          - node.labels.type != restricted
      mode: replicated
      replicas: 1
#      placement:
#        constraints:
#          - node.role == worker
      restart_policy:
        condition: on-failure


#################### Heimdall #######################################
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.7.6
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - heimdall_nfs:/config:subpath=config
    networks:
      - proxy_private
#    ports:
#      - "8080:80"
#      - "8443:443"
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.heimdall.rule=Host(`${HEIMDALL_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.heimdall.entrypoints=websecure"
        - "traefik.http.routers.heimdall.tls=true"
        - "traefik.http.routers.heimdall.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.heimdall.loadbalancer.server.port=80"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.heimdall.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.heimdall.tls.domains[0].sans=*.${BASE_DOMAIN}"
      placement:
        constraints:
          - node.labels.type != restricted
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

########################## Excalidraw ############################3
  excalidraw:
    image: excalidraw/excalidraw:latest
#    ports:
#      - "5000:80"
    networks:
      - tools
      - proxy_private
    environment:
      # This tells the browser where to find the collaboration server
      # Replace 'excalidraw.yourdomain.com' with your actual IP or Domain
      - VITE_APP_WS_SERVER_URL=http://tools_excalidraw-room
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.excalidraw.rule=Host(`${EXCALIDRAW_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.excalidraw.entrypoints=websecure"
        - "traefik.http.routers.excalidraw.tls=true"
        - "traefik.http.routers.excalidraw.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.excalidraw.loadbalancer.server.port=80"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.excalidraw.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.excalidraw.tls.domains[0].sans=*.${BASE_DOMAIN}"
      placement:
        constraints:
          - node.labels.type != restricted
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  # The Collaboration Backend (Socket server)
  excalidraw-room:
    image: excalidraw/excalidraw-room:latest
    networks:
      - tools
#      - proxy_private
#    ports:
#      - "8081:8080"
    deploy:
      replicas: 1
#      placement:
#        constraints:
#          - node.role == worker # Can run anywhere
      restart_policy:
        condition: on-failure


############################### BentoPDF ###########################
  bento-pdf:
    image: ghcr.io/alam00000/bentopdf:latest
    networks:
      - proxy_private
#    ports:
#      - "8080:8080"
    environment:
      - NODE_ENV=production
    # Uncomment the volumes line if you need to persist custom templates or assets
    # volumes:
    #   - ./templates:/app/templates
    restart: unless-stopped
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.bento-pdf.rule=Host(`${BENTOPDF_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.bento-pdf.entrypoints=websecure"
        - "traefik.http.routers.bento-pdf.tls=true"
        - "traefik.http.routers.bento-pdf.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.bento-pdf.loadbalancer.server.port=8080"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.bento-pdf.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.bento-pdf.tls.domains[0].sans=*.${BASE_DOMAIN}"
      placement:
        constraints:
          - node.labels.type != restricted
      replicas: 1


networks:
    proxy_private:
      external: true
      name: proxy_private
    tools:
      name: tools-network
      driver: overlay
      attachable: true

volumes:
  heimdall_nfs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_ADDRESS},nfsvers=3,nolock,soft,rw"
      device: ":${HEIMDALL_CONFIG_NFS_DIRECTORY}"