version: '3.8'

services:
  gluetun:
    image: qmcgaw/gluetun:v3.41
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${GLUETUN_SERVER_COUNTRIES}
    networks:
      - public-torrent-network
      - internal-only-torrent-network
    deploy:
      replicas: 1
      placement:
        constraints:
#          - node.labels.docker_mount == true
          - node.labels.type != restricted

#  qbittorrent:
#    image: lscr.io/linuxserver/qbittorrent:latest
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/London
#      - WEBUI_PORT=8080
#    networks:
#      - vpn_net
#    deploy:
#      placement:
#        constraints: [node.role == worker] # Must be same node as gluetun
#    depends_on:
#      - gluetun

networks:
  internal-only-torrent-network:
    driver: overlay
    internal: true  # STRICTLY isolated; no external ingress/egress
  public-torrent-network:
    driver: overlay
    internal: false # Standard network with internet access