services:
  # INDEXER MANAGER
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.3.5
    networks:
      - arr_network
      - proxy_private
      - kuma_network
#    ports:+
#      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - type: volume
        source: arr-data
        target: /config
        volume:
          subpath: prowlarr/config
          nocopy: true
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.prowlarr.rule=Host(`${PROWLARR_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.prowlarr.entrypoints=websecure"
        - "traefik.http.routers.prowlarr.tls=true"
        - "traefik.http.routers.prowlarr.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.prowlarr.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.prowlarr.tls.domains[0].sans=*.${BASE_DOMAIN}"
        - "kuma.arr.group.name=ARR Stack"
        - "kuma.prowlarr.http.name=Prowlarr"
        - "kuma.prowlarr.http.url=http://prowlarr:9696"
        - "kuma.prowlarr.http.interval=300"
        - "kuma.prowlarr.http.parent_name=arr"
      replicas: 1
      placement:
        constraints:
          - node.labels.docker_mount == true
          - node.labels.type != restricted
  # MOVIES
  radarr:
    image: lscr.io/linuxserver/radarr:6.1.1
    networks:
      - arr_network
      - proxy_private
      - kuma_network
#    ports:
#      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - type: volume
        source: arr-data
        target: /config
        volume:
          subpath: radarr/config
          nocopy: true
      - /mnt/video/data/movie:/movies
      - /mnt/video/completed-downloads:/downloads
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.radarr.rule=Host(`${RADARR_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.radarr.entrypoints=websecure"
        - "traefik.http.routers.radarr.tls=true"
        - "traefik.http.routers.radarr.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.radarr.loadbalancer.server.port=7878"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.radarr.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.radarr.tls.domains[0].sans=*.${BASE_DOMAIN}"
        - "kuma.radarr.http.name=Radarr"
        - "kuma.radarr.http.url=http://radarr:7878"
        - "kuma.radarr.http.interval=300"
        - "kuma.radarr.http.parent_name=arr"
      replicas: 1
      placement:
        constraints:
          - node.labels.docker_mount == true
          - node.labels.video_mount == true
          - node.labels.type != restricted
#
  # TV SHOWS
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.17
    networks:
      - arr_network
      - proxy_private
      - kuma_network
#    ports:
#      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - type: volume
        source: arr-data
        target: /config
        volume:
          subpath: sonarr/config
          nocopy: true
      - /mnt/video/data/shows:/tvseries
      - /mnt/video/completed-downloads:/downloads
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.sonarr.rule=Host(`${SONARR_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.sonarr.entrypoints=websecure"
        - "traefik.http.routers.sonarr.tls=true"
        - "traefik.http.routers.sonarr.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.sonarr.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.sonarr.tls.domains[0].sans=*.${BASE_DOMAIN}"
        - "kuma.sonarr.http.name=Sonarr"
        - "kuma.sonarr.http.url=http://sonarr:8989"
        - "kuma.sonarr.http.interval=300"
        - "kuma.sonarr.http.parent_name=arr"
      replicas: 1
      placement:
        constraints:
          - node.labels.docker_mount == true
          - node.labels.video_mount == true
          - node.labels.type != restricted
#
#
# NEW: MUSIC
  lidarr:
    image: lscr.io/linuxserver/lidarr:3.1.0
    networks:
      - arr_network
      - proxy_private
      - kuma_network
#    ports:
#      - 8686:8686
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - type: volume
        source: arr-data
        target: /config
        volume:
          subpath: lidarr/config
          nocopy: true
      - /mnt/video/data/music:/music
      - /mnt/video/completed-downloads:/downloads
#      - /path/to/music:/music #optional
#      - /path/to/downloads:/downloads #optional
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.lidarr.rule=Host(`${LIDARR_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.lidarr.entrypoints=websecure"
        - "traefik.http.routers.lidarr.tls=true"
        - "traefik.http.routers.lidarr.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.lidarr.loadbalancer.server.port=8686"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.lidarr.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.lidarr.tls.domains[0].sans=*.${BASE_DOMAIN}"
        - "kuma.lidarr.http.name=Lidarr"
        - "kuma.lidarr.http.url=http://lidarr:8686"
        - "kuma.lidarr.http.interval=300"
        - "kuma.lidarr.http.parent_name=arr"
      replicas: 1
      placement:
        constraints:
          - node.labels.docker_mount == true
          - node.labels.video_mount == true
          - node.labels.type != restricted

  listenarr:
    image: ghcr.io/listenarrs/listenarr:canary
#    ports:
#      - "4545:4545"
    networks:
      - arr_network
      - proxy_private
      - kuma_network
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
#      - LISTENARR_PUBLIC_URL=https://your-domain.com ## OPTIONAL: Used by Discord Bot
    volumes:
      - type: volume
        source: arr-data
        target: /config
        volume:
          subpath: listenarr/config
          nocopy: true
#      - listenarr_data:/app/config
      - /mnt/video/data/audio-books:/audiobooks #optional
      - /mnt/video/completed-downloads:/downloads
    restart: unless-stopped
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.listenarr.rule=Host(`${LISTENARR_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.listenarr.entrypoints=websecure"
        - "traefik.http.routers.listenarr.tls=true"
        - "traefik.http.routers.listenarr.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.listenarr.loadbalancer.server.port=4545"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.listenarr.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.listenarr.tls.domains[0].sans=*.${BASE_DOMAIN}"
        - "kuma.listenarr.http.name=Listenarr"
        - "kuma.listenarr.http.url=http://listenarr:4545"
        - "kuma.listenarr.http.interval=300"
        - "kuma.listenarr.http.parent_name=arr"
      replicas: 1
      placement:
        constraints:
          - node.labels.docker_mount == true
          - node.labels.video_mount == true
          - node.labels.type != restricted


#  # NEW: BOOKS
#  lazy-librarian:
#    image: lscr.io/linuxserver/lazylibrarian:latest # Develop branch is often preferred for Readarr
#    networks:
#      - arr_network
#      - proxy_private
##    ports:
##      - 5299:5299
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=America/Denver
#    volumes:
#      - type: volume
#        source: arr-data
#        target: /config
#        volume:
#          subpath: lazylibrarian/config
#          nocopy: true
#      - /mnt/video/data/books:/books
#      - /mnt/video/completed-downloads:/downloads
##      - /path/to/downloads/:/downloads
##      - /path/to/data/:/books #optional
#    deploy:
#      labels:
#        - "traefik.enable=true"
#        #        # The URL you will use to access Nextcloud
#        - "traefik.http.routers.lazylibrarian.rule=Host(`${LAZYLIBRARIAN_SUBDOMAIN}.${BASE_DOMAIN}`)"
#        - "traefik.http.routers.lazylibrarian.entrypoints=websecure"
#        - "traefik.http.routers.lazylibrarian.tls=true"
#        - "traefik.http.routers.lazylibrarian.tls.certresolver=mydnschallenge"
#        #        # Critical for Swarm: Specify the internal container port
#        - "traefik.http.services.lazylibrarian.loadbalancer.server.port=5299"
#        #        # Ensure Traefik uses the correct network for routing
#        - "traefik.docker.network=proxy_private"
#        # This line is key: it tells Traefik to look for the cert containing these domains
#        - "traefik.http.routers.lazylibrarian.tls.domains[0].main=${BASE_DOMAIN}"
#        - "traefik.http.routers.lazylibrarian.tls.domains[0].sans=*.${BASE_DOMAIN}"
#      replicas: 1
#      placement:
#        constraints:
#          - node.labels.docker_mount == true
#          - node.labels.video_mount == true
#          - node.labels.type != restricted

  flaresolverr:
    # Use the official GHCR image for the most up-to-date 2026 releases
    image: ghcr.io/flaresolverr/flaresolverr:latest
    networks:
      - arr_network
    environment:
      - LOG_LEVEL=info
      - TZ=America/New_York # Set your timezone
    # FlareSolverr doesn't need to expose ports to the web if
    # Prowlarr is on the same overlay network.
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G  # Chromium needs some breathing room
          cpus: '0.5'
      placement:
        constraints:
          - node.labels.type != restricted

networks:
  arr_network:
    driver: overlay
    attachable: true
  proxy_private:
    external: true
  kuma_network:
    external: true
    name: kuma_network

volumes:
  arr-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_ADDRESS},nfsvers=4,nolock,soft,rw" # Replace with your NFS Server IP
      device: ":${ARR_NFS_DIRECTORY}"