version: '3.8'

services:
  adguard-primary:
    image: adguard/adguardhome:v0.107.71
    hostname: adguard-dns-primary
    environment:
      # Find your PUID and PGID by running "id $user" in your terminal
      - PUID=0
      - PGID=0
      - TZ=America/Denver # Replace with your timezone
    networks:
      - dns_net
      - proxy_private
    volumes:
      - /mnt/docker/adguard/config:/opt/adguardhome/conf
      - /mnt/docker/adguard/work:/opt/adguardhome/work
    ports:
      # Host mode ensures you see client IPs in the dashboard
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      # Setup/Web UI
#      - target: 3000
#        published: 3000
#        protocol: tcp
#      - target: 80
#        published: 80
#        protocol: tcp
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.adguard-primary.rule=Host(`${SUBDOMAIN_ONE}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.adguard-primary.entrypoints=websecure"
        - "traefik.http.routers.adguard-primary.tls=true"
        - "traefik.http.routers.adguard-primary.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.adguard-primary.loadbalancer.server.port=80"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.adguard-primary.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.adguard-primary.tls.domains[0].sans=*.${BASE_DOMAIN}"
        - "kuma.dns.group.name=DNS"
        - "kuma.adguard-one.http.name=Adguard 1"
        - "kuma.adguard-one.http.url=http://adguard-primary:80"
        - "kuma.adguard-one.http.interval=300"
        - "kuma.adguard-one.http.parent_name=dns"
      mode: replicated
      replicas: 1
      placement:
        constraints:
          # This ensures it ONLY runs on the labeled node
          - node.labels.static_ip == 192.168.4.47
      restart_policy:
        condition: on-failure

  adguard-secondary:
    image: adguard/adguardhome:v0.107.71
    hostname: adguard-dns-secondary
    environment:
      # Find your PUID and PGID by running "id $user" in your terminal
      - PUID=0
      - PGID=0
      - TZ=America/Denver # Replace with your timezone
    networks:
      - dns_net
      - proxy_private
    volumes:
      - /mnt/docker/adguard/config:/opt/adguardhome/conf
      - /mnt/docker/adguard/work-secondary:/opt/adguardhome/work
    ports:
      # Host mode ensures you see client IPs in the dashboard
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      # Setup/Web UI
#      - target: 3000
#        published: 3000
#        protocol: tcp
#      - target: 80
#        published: 80
#        protocol: tcp
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.adguard-secondary.rule=Host(`${SUBDOMAIN_TWO}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.adguard-secondary.entrypoints=websecure"
        - "traefik.http.routers.adguard-secondary.tls=true"
        - "traefik.http.routers.adguard-secondary.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.adguard-secondary.loadbalancer.server.port=80"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.adguard-secondary.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.adguard-secondary.tls.domains[0].sans=*.${BASE_DOMAIN}"
        - "kuma.adguard-two.http.name=Adguard 2"
        - "kuma.adguard-two.http.url=http://adguard-secondary:80"
        - "kuma.adguard-two.http.interval=300"
        - "kuma.adguard-two.http.parent_name=dns"
      mode: replicated
      replicas: 1
      placement:
        constraints:
          # This ensures it ONLY runs on the labeled node
          - node.labels.static_ip == 192.168.4.22
      restart_policy:
        condition: on-failure

networks:
  dns_net:
    driver: overlay
    attachable: true
  proxy_private:
    external: true
    name: proxy_private