version: '3.8'

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    volumes:
      - /mnt/photo:/data
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - db_password
    environment:
      DB_URL: ${DB_URL}
#      DB_HOSTNAME: database
#      DB_USERNAME: ${DB_USERNAME}
#      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      # If using secrets (recommended):
#      DB_PASSWORD_FILE: /run/secrets/db_password
      # Redis
      REDIS_HOSTNAME: redis
      # General
      IMMICH_VERSION: ${IMMICH_VERSION}
#    env_file:
#      - immich.env
#    ports:
#      - 2283:2283
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.immich-server.rule=Host(`${IMMICH_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.immich-server.entrypoints=websecure"
        - "traefik.http.routers.immich-server.tls=true"
        - "traefik.http.routers.immich-server.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.immich-server.loadbalancer.server.port=5678"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.immich-server.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.immich-server.tls.domains[0].sans=*.${BASE_DOMAIN}"
      placement:
        constraints:
          - node.labels.photo_mount == true
          - node.labels.docker_mount == true
          - node.labels.type != restricted
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - immich-network
      - proxy_private

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}
    volumes:
      - model-cache:/cache
#    env_file:
#      - immich.env
    deploy:
      placement:
        constraints:
          - node.labels.type != restricted
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - immich-network

  redis:
    image: docker.io/valkey/valkey:${REDIS_VERSION}
    deploy:
      placement:
        constraints:
          - node.labels.type != restricted
      restart_policy:
        condition: on-failure
    networks:
      - immich-network

#  database:
#    image: ghcr.io/tensorchord/vchord-postgres:${DATABASE_VERSION}
#    networks:
#      - immich-network
#    environment:
#      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
#      POSTGRES_USER: ${DB_USERNAME}
#      POSTGRES_DB: ${DB_DATABASE_NAME}
#      POSTGRES_INITDB_ARGS: '--data-checksums'
#      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
#      # DB_STORAGE_TYPE: 'HDD'
#    volumes:
#      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
#      - /mnt/docker/immich/postgres:/var/lib/postgresql/data
#    secrets:
#      - db_password
#    deploy:
#      replicas: 1
#      restart_policy:
#        condition: on-failure

volumes:
  model-cache:

networks:
  immich-network:
    driver: overlay
    name: immich-network
  proxy_private:
    external: true

secrets:
  db_password:
    external: true
    name: immich-database-password