version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v3.10.0
#    ports:
#      - "9090:9090"
    networks:
      - monitor-network
    user: 0:0
    volumes:
      - /mnt/docker/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /mnt/docker/prometheus/data:/prometheus
    deploy:
      placement:
        constraints:
          - node.labels.docker_mount == true
          - node.labels.type != restricted
      replicas: 1
#      placement:
#        constraints:
#          - node.role == manager

  grafana:
    image: grafana/grafana:12.3
    networks:
      - monitor-network
      - proxy_private
      - dns_network
#    ports:
#      - "3000:3000"
    volumes:
      - /mnt/docker/grafana/data:/var/lib/grafana
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.grafana.rule=Host(`${GRAFANA_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.tls=true"
        - "traefik.http.routers.grafana.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.grafana.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.grafana.tls.domains[0].sans=*.${BASE_DOMAIN}"
      placement:
        constraints:
          - node.labels.docker_mount == true
          - node.labels.type != restricted
      replicas: 1
#      placement:
#        constraints:
#          - node.role == manager

  node-exporter:
    image: prom/node-exporter:v1.10.2
    networks:
      - monitor-network
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host)($$|/)'
      - '--collector.textfile.directory=/etc/nodename'
    environment:
      - NODE_ID={{.Node.ID}}
    hostname: "{{.Node.Hostname}}"
    deploy:
      mode: global  # This runs it on EVERY node automatically

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    networks:
      - monitor-network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global  # This collects container stats from EVERY node

networks:
  monitor-network:
    name: monitor_network
    attachable: true
  dns_network:
    external: true
    name: dns_dns_net
  proxy_private:
    external: true
    name: proxy_private