version: '3.8'

services:
  maria-db:
    image: mariadb:12.2.2
    networks:
      - maria_db_net
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/maria_db_root_password
      MYSQL_DATABASE: "node_proxy_manager"
      MYSQL_USER: "node_proxy_manager"
      MYSQL_PASSWORD: /run/secrets/maria_db_user_node_proxy_manager_password
    volumes:
      - type: volume
        source: maria_db_data
        target: /var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.labels.type == database
      resources:
        limits:
          memory: 1024M # MariaDB can be hungry; 512MB is safe for a Pi
      restart_policy:
        condition: on-failure

networks:
  maria_db_net:
    driver: overlay
    attachable: true # Allows other stacks (like the NPM stack) to connect

volumes:
  maria_db_data:
    driver: local