version: "3.8"

services:
  # Database Service
#  db:
#    image: postgres:15-alpine
#    environment:
#      - POSTGRES_DB=opencloud
#      - POSTGRES_USER=opencloud_user
#      - POSTGRES_PASSWORD=${DB_PASSWORD}
#    volumes:
#      - db_data:/var/lib/postgresql/data
#    deploy:
#      placement:
#        constraints: [node.role == manager]

  # Main OpenCloud Application
  app:
    image: ${OPEN_CLOUD_VERSION} # Use the specific opencloud-eu image
    networks:
      - open-cloud-net
      - proxy-private
    environment:
#      - OC_DOMAIN=${DOMAIN}
#      - DB_TYPE=postgres
#      - DB_HOST=${DB_HOST}
#      - DB_NAME=opencloud
#      - DB_USER=opencloud_user
#      - DB_PASS=${DB_PASSWORD}
      - OC_JWT_SECRET=${JWT_SECRET}
      - OC_TRANSFER_SECRET=${TRANSFER_SECRET}
      - OC_MACHINE_AUTH_API_KEY=${MACHINE_API_KEY}
      - OC_ADMIN_USER_ID=${ADMIN_USER_UUID}
      - OC_SYSTEM_USER_ID=${SYSTEM_USER_UUID}
      - PROXY_HTTP_ADDR=0.0.0.0:9200
      - OC_URL=https://${DOMAIN}
      - OC_INSECURE=true
      - IDM_ADMIN_PASSWORD=${IDM_ADMIN_PASSWORD}
#    ports:
#      - "8080:80"
    volumes:
#      - open-cloud-data:/var/lib/opencloud:subpath=data
#      - open-cloud-data:/etc/opencloud:subpath=config
      - /mnt/docker/open-cloud/data:/var/lib/opencloud
      - /mnt/docker/open-cloud/config:/etc/opencloud
    deploy:
      replicas: 1

networks:
  open-cloud-net:
    driver: overlay
    attachable: true
    name: open-cloud-network
  proxy-private:
    external: true
    name: proxy_private
#volumes:
#  open-cloud-data:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: "addr=${NFS_ADDRESS},nfsvers=3,nolock,soft,rw"
#      device: ":${OPENCLOUD_NFS_DIRECTORY}"