services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:2026.3"
    volumes:
      - /mnt/docker/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - "8123:8123"
    networks:
      - smart-home-network
      - dns_network
      - proxy_private
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.homeassistant.rule=Host(`${HOMEASSISTANT_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.homeassistant.entrypoints=websecure"
        - "traefik.http.routers.homeassistant.tls=true"
        - "traefik.http.routers.homeassistant.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.homeassistant.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.homeassistant.tls.domains[0].sans=*.${BASE_DOMAIN}"
      placement:
        constraints:
          - node.labels.docker_mount == true
          - node.labels.type != restricted
      mode: replicated
      replicas: 1
#      placement:
#        constraints:
#          - node.hostname == your-smart-home-node

#  # Optional but highly recommended: MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    restart: unless-stopped
    networks:
      - smart-home-network
      - proxy_private
#    ports:
#      - "1883:1883"
#      - "9001:9001"
    volumes:
      - mosquitto_nfs:/mosquitto
#      - mosquitto_nfs:/mosquitto/data:subpath=data
#      - mosquitto_nfs:/mosquitto/log:subpath=log
    environment:
      - TZ=America/Denver
#
#  zigbee2mqtt:
#    container_name: zigbee2mqtt
#    image: ghcr.io/koenkk/zigbee2mqtt
#    restart: unless-stopped
#    volumes:
#      - /PATH_TO_YOUR_CONFIG/zigbee2mqtt:/app/data
#      - /run/udev:/run/udev:ro
#    ports:
#      - "8080:8080" # Frontend UI
#    devices:
#      # Replace with your actual Zigbee stick path
#      - /dev/serial/by-id/usb-Sonoff_Zigbee_3.0_USB_Dongle_Plus-if00-port0:/dev/ttyACM0
#    environment:
#      - TZ=America/New_York
#
#  zwave-js-ui:
#    image: zwavejs/zwave-js-ui:11.14
#    environment:
#      - TZ=America/Denver
#    volumes:
#      - /mnt/docker/zwave:/usr/src/app/store
#      - /dev/serial/by-id/${ZWAVE_DEVICE_ID}:/dev/zwave
#    networks:
#      - proxy_private
#      - dns_network
#      - smart-home-network
##    ports:
##      - "8091:8091" # Frontend UI
##      - "3000:3000" # Z-Wave JS Websocket (Preferred for HA)
#    deploy:
#      mode: replicated
#      replicas: 1
#      placement:
#        constraints:
#          - node.labels.zwave == true

networks:
  smart-home-network:
    driver: overlay
    attachable: true
    name: smart-home-network
  dns_network:
    external: true
    name: dns_dns_net
  proxy_private:
    external: true
    name: proxy_private

volumes:
  mosquitto_nfs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_ADDRESS},nfsvers=3,nolock,soft,rw"
      device: ":${MOSQUITTO_NFS_DIRECTORY}"