version: '3.8'

services:
  n8n:
    image: n8nio/n8n:2.11.4
    networks:
      - proxy_private
    environment:
      - N8N_HOST=automate.derek-crew.com
      - NODE_ENV=production
      - GENERIC_TIMEZONE=America/Denver
#      - NODES_EXCLUDE=[]
    volumes:
      - /mnt/docker/n8n:/home/node/.local/share/n8n
#    ports:
#      - target: 5678
#        published: 5678
#        protocol: tcp
#        mode: host
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure


  uptime-kuma:
    image: louislam/uptime-kuma:2.2.1
    networks:
      - proxy_private
    volumes:
      - /mnt/docker/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
#    ports:
#      - target: 3001
#        published: 3001
#        protocol: tcp
#        mode: host
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure


  ntfy:
    image: binwiederhier/ntfy:v2.19.1
    command: serve
    environment:
      - TZ=America/Denver # Change to your timezone, e.g., America/New_York
    volumes:
      - /mnt/docker/ntfy/cache:/var/cache/ntfy
      - /mnt/docker/ntfy/lib:/var/lib/ntfy
      # - ./server.yml:/etc/ntfy/server.yml:ro # Uncomment if using a custom config file
    networks:
      - proxy_private
      - smart_home
#    ports:
#      - target: 80
#        published: 8080 # Change this to your desired public port
#        mode: ingress
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
#      placement:
#        constraints:
          # Pin to a specific node if you aren't using shared storage (NFS/Gluster)
          # Get node name via 'docker node ls'
#          - node.hostname == my-main-node
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 64M

#volumes:
#  n8n_data:
#    driver: local

networks:
    proxy_private:
      external: true
      name: proxy_private
    smart_home:
      external:  true
      name: smart-home-network