version: '3.8'

services:
  n8n:
    image: n8nio/n8n:2.11.4
    networks:
      - proxy_private
    environment:
      - N8N_HOST=automate.derek-crew.com
      - NODE_ENV=production
      - GENERIC_TIMEZONE=America/Denver
#      - NODES_EXCLUDE=[]
    volumes:
      - /mnt/docker/n8n:/home/node/.local/share/n8n
#    ports:
#      - target: 5678
#        published: 5678
#        protocol: tcp
#        mode: host
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.n8n.rule=Host(`${N8N_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.n8n.entrypoints=websecure"
        - "traefik.http.routers.n8n.tls=true"
        - "traefik.http.routers.n8n.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.n8n.loadbalancer.server.port=5678"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.n8n.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.n8n.tls.domains[0].sans=*.${BASE_DOMAIN}"
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.docker_mount == true
          - node.labels.type != restricted


  uptime-kuma:
    image: louislam/uptime-kuma:2.2.1
    networks:
      - proxy_private
    volumes:
      - /mnt/docker/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
#    ports:
#      - target: 3001
#        published: 3001
#        protocol: tcp
#        mode: host
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.uptime-kuma.rule=Host(`${UPTIME_KUMA_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
        - "traefik.http.routers.uptime-kuma.tls=true"
        - "traefik.http.routers.uptime-kuma.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.uptime-kuma.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.uptime-kuma.tls.domains[0].sans=*.${BASE_DOMAIN}"
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.docker_mount == true
          - node.labels.type != restricted

  auto-kuma:
    image: bigmoby/auto-kuma:latest
    environment:
      - KUMA_URL=http://kuma:3001
      # If you set up a user, add credentials:
      # - KUMA_USERNAME=admin
      # - KUMA_PASSWORD=yourpassword
      - DOCKER_SOCKET=/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy_private
    deploy:
      placement:
        constraints:
          - node.labels.type != restricted


  ntfy:
    image: binwiederhier/ntfy:v2.19.1
    command: serve
    environment:
      - TZ=America/Denver # Change to your timezone, e.g., America/New_York
    volumes:
      - /mnt/docker/ntfy/cache:/var/cache/ntfy
      - /mnt/docker/ntfy/lib:/var/lib/ntfy
      # - ./server.yml:/etc/ntfy/server.yml:ro # Uncomment if using a custom config file
    networks:
      - proxy_private
      - smart_home
#    ports:
#      - target: 80
#        published: 8080 # Change this to your desired public port
#        mode: ingress
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.ntfy.rule=Host(`${NTFY_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.ntfy.entrypoints=websecure"
        - "traefik.http.routers.ntfy.tls=true"
        - "traefik.http.routers.ntfy.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.ntfy.loadbalancer.server.port=80"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.ntfy.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.ntfy.tls.domains[0].sans=*.${BASE_DOMAIN}"
        - "kuma.check=true"
        - "kuma.name=NTFY"
        - "kuma.url=http://ntfy:80"
        - "kuma.type=http"
        - "kuma.interval=60"
      replicas: 1
      restart_policy:
        condition: on-failure
#      placement:
#        constraints:
          # Pin to a specific node if you aren't using shared storage (NFS/Gluster)
          # Get node name via 'docker node ls'
#          - node.hostname == my-main-node
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 64M
      placement:
        constraints:
          - node.labels.docker_mount == true
          - node.labels.type != restricted

#volumes:
#  n8n_data:
#    driver: local

networks:
    proxy_private:
      external: true
      name: proxy_private
    smart_home:
      external:  true
      name: smart-home-network