version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:10
#    ports:
#      - "8096:8096"
    networks:
      - media_network
      - proxy_public
      - dns_network
    environment:
      - JELLYFIN_PublishedServerUrl=${DOMAIN}
    volumes:
      - /mnt/docker/jellyfin/config:/config
#      - jellyfin_cache:/cache
      - /mnt/video/data/movie:/media/movie:ro
      - /mnt/video/data/shows:/media/shows:ro
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == media # Or specify a node with GPU for transcoding


  jellyseer:
    image:  ghcr.io/seerr-team/seerr:v3.1.0
    networks:
      - media_network
      - proxy_public
      - dns_network
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Denver
    user: 1000:1000
    volumes:
      - jellyseer_nfs:/app/config:subpath=config
    deploy:
      replicas: 1

  test-jellyseer:
    image:  fallenbagel/jellyseerr:2.7.3
    networks:
      - media_network
      - proxy_public
      - dns_network
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Denver
#    user: 1000:1000
#    volumes:
#      - jellyseer_nfs:/app/config:subpath=config
    deploy:
      replicas: 1

networks:
  media_network:
    driver: overlay
    attachable: true
    name: media-network
  proxy_public:
    external: true
  dns_network:
    external: true
    name: dns_dns_net

volumes:
  jellyfin_cache:
    driver: local
  jellyseer_nfs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_ADDRESS},nfsvers=3,nolock,soft,rw"
      device: ":${SEERR_CONF_NFS_DIRECTORY}"