services:
  jellyfin:
    image: jellyfin/jellyfin:10
#    ports:
#      - "8096:8096"
    networks:
      - media_network
      - proxy_private
      - dns_network
    environment:
      - JELLYFIN_PublishedServerUrl=${DOMAIN}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /mnt/docker/jellyfin/config:/config
      - jellyfin_cache:/cache
      - /mnt/video/data/movie:/media/movie:ro
      - /mnt/video/data/shows:/media/shows:ro
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.jellyfin.entrypoints=websecure"
        - "traefik.http.routers.jellyfin.tls=true"
        - "traefik.http.routers.jellyfin.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.jellyfin.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.jellyfin.tls.domains[0].sans=*.${BASE_DOMAIN}"
      placement:
        constraints:
          - node.labels.docker_mount == true
          - node.labels.video_mount == true
          - node.labels.media_node == true
          - node.labels.gpu == true
      resources:
        reservations:
#          cpus: '2.0'
#          memory: 8192M
          generic_resources:
            - discrete_resource_spec:
                kind: 'NVIDIA-GPU'
                value: 0


  jellyseer:
    image:  ghcr.io/seerr-team/seerr:v3.1.0
    networks:
      - media_network
      - proxy_private
      - dns_network
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Denver
    user: 1000:1000
    volumes:
      - jellyseer_nfs:/app/config:subpath=config
    deploy:
      labels:
        - "traefik.enable=true"
        #        # The URL you will use to access Nextcloud
        - "traefik.http.routers.jellyseer.rule=Host(`${JELLYSEER_SUBDOMAIN}.${BASE_DOMAIN}`)"
        - "traefik.http.routers.jellyseer.entrypoints=websecure"
        - "traefik.http.routers.jellyseer.tls=true"
        - "traefik.http.routers.jellyseer.tls.certresolver=mydnschallenge"
        #        # Critical for Swarm: Specify the internal container port
        - "traefik.http.services.jellyseer.loadbalancer.server.port=5055"
        #        # Ensure Traefik uses the correct network for routing
        - "traefik.docker.network=proxy_private"
        # This line is key: it tells Traefik to look for the cert containing these domains
        - "traefik.http.routers.jellyseer.tls.domains[0].main=${BASE_DOMAIN}"
        - "traefik.http.routers.jellyseer.tls.domains[0].sans=*.${BASE_DOMAIN}"
      replicas: 1
      placement:
        constraints:
          - node.labels.type != restricted


networks:
  media_network:
    driver: overlay
    attachable: true
    name: media-network
  proxy_public:
    external: true
  dns_network:
    external: true
    name: dns_dns_net
  proxy_private:
    external: true

volumes:
  jellyfin_cache:
    driver: local
  jellyseer_nfs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_ADDRESS},nfsvers=3,nolock,soft,rw"
      device: ":${SEERR_CONF_NFS_DIRECTORY}"